--CREATE TABLE Teachers(
--Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
--FirstName NVARCHAR (20) NOT NULL,
--LastName NVARCHAR (20) NOT NULL,
--UserId NVARCHAR (450) FOREIGN KEY REFERENCES AspNetUsers(Id)
--);

--CREATE TABLE Classrooms(
--Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
--TeacherId INT FOREIGN KEY REFERENCES Teachers(Id),
--ClassName NVARCHAR(50) NOT NULL,
--ClassAvg FLOAT
--);

--CREATE TABLE Students(
--Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
--FirstName NVARCHAR (20) NOT NULL,
--LastName NVARCHAR (20) NOT NULL,
--AverageGrade FLOAT,
--UserId NVARCHAR (450) FOREIGN KEY REFERENCES AspNetUsers(Id),
--ClassroomId INT FOREIGN KEY REFERENCES Classrooms(Id)
--);

--CREATE TABLE Quizes(
--Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
--QuizType NVARCHAR(25)
--);

--CREATE TABLE Grades(
--Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
--Grade FLOAT,
--StudentId INT FOREIGN KEY REFERENCES Students(Id),
--QuizId INT FOREIGN KEY REFERENCES Quizes(Id)
--);

--CREATE TABLE Questions(
--Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
--QuizId INT FOREIGN KEY REFERENCES Quizes(Id),
--Question NVARCHAR(150)
--);

--CREATE TABLE Questionsbank(
--Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
--QuizId INT FOREIGN KEY REFERENCES Quizes(Id),
--QuestionId INT FOREIGN KEY REFERENCES Questions(Id)
--);